<?php

namespace App;

class RouteName
{
    const HOME = 'HOME';
    const ADVERT_CREATE = 'ADVERT_CREATE';
    const ADVERT_DELETE = 'ADVERT_DELETE';
    const ADVERT_SHOW_EDIT_FORM = 'ADVERT_SHOW_EDIT_FORM';
    const ADVERT_CHANGE = 'ADVERT_CHANGE';
    const ADVERT_SHOW_CREATE_FORM= 'ADVERT_SHOW_CREATE_FORM';
    const ADVERT_SHOW = 'ADVERT_SHOW_ALL';
    const CATEGORY_CREATE = 'CATEGORY_CREATE';
    const CATEGORY_DELETE = 'CATEGORY_DELETE';
    const CATEGORY_SHOW_CREATE_FORM = 'CATEGORY_SHOW_CREATE_FORM';
    const CATEGORY_SHOW_EDIT_FORM = 'CATEGORY_SHOW_EDIT_FORM';
    const CATEGORY_CHANGE = 'CATEGORY_CHANGE';
    const CATEGORY_SHOW = 'CATEGORY_SHOW';
    const PURCHASE_SHOW = 'PURCHASE_SHOW';
}
